---
# handlers file for clickhouse
- name: restart-ch
  service:
    name: "clickhouse-server"
    state: restarted
  become: true

- name: restart-ch-exporter
  service:
    name: clickhouse_exporter
    state: restarted
  become: true
